######################################################################
# Automatically generated by qmake (3.0) mer. févr. 24 15:30:59 2016
######################################################################

TEMPLATE = app
TARGET = afk
INCLUDEPATH += .
LIBS += -lainl16 -lsfml-network -lsfml-system
QMAKE_CXXFLAGS += -std=c++11

# Input
SOURCES += \
    afk.cpp
